// Mocks generated by Mockito 5.2.0 from annotations
// in fluttertest/test/test_list_product.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:fluttertest/data/models/product_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

import 'test_list_product.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ProductServiceTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductServiceTest extends _i1.Mock
    implements _i2.ProductServiceTest {
  MockProductServiceTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Product>> getAllProduct() =>
      (super.noSuchMethod(Invocation.method(#getAllProduct, []),
              returnValue: Future<List<_i4.Product>>.value(<_i4.Product>[]))
          as _i3.Future<List<_i4.Product>>);
}
